version: 2

sources:
  - name: jaffle_shop
    description: This is a replica of the Postgres database used by our app
    database: dbt-tutorial
    schema: jaffle_shop
    freshness:
      error_after:
        count: 7
        period: day
      warn_after:
        count: 1
        period: day
    loaded_at_field: _etl_loaded_at
    tables:
      - name: customers
        description: One record per customer (raw)
        freshness: null
        columns:
          - name: id
            description: Primary Key for customer id
            data_tests:
            - not_null
            - unique
      - name: orders
        description: One record per order (raw). Includes cancelled and deleted orders.
        columns:
          - name: id
            data_tests:
            - not_null
            - unique
        

  - name: stripe
    description: This is a replica of the Postgres database used by Stripe to handle our payments data
    database: dbt-tutorial
    schema: stripe
    tables:
      - name: payment
        description: payment information for orders
