# ~/.dbt/profiles.yml  (or set DBT_PROFILES_DIR to your repo)
default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('BIGQUERY_PROJECT') }}"     # GCP Project ID
      dataset: "{{ env_var('DBT_DATASET','dbt_fcoupe') }}"  # BigQuery dataset == dbt "schema"
      location: "{{ env_var('BIGQUERY_LOCATION','US') }}"      # e.g. US, EU, us-central1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"  # path to keyfile.json
      threads: 8
